services:
  simple-api:
    build: ./simple-api
    environment:
      - PORT=3000
    networks:
      - simple

  simple-service:
    depends_on:
      - simple-api
    build: ./simple-service
    environment:
      - API_URL=http://simple-api:3000/
    networks:
      - simple

networks:
  simple: